# Simulation Parameters
simulation:
  num_episodes: 3      # Number of episodes to run
  max_steps: 1000      # Max steps per episode
  render_mode: 'human' # 'human', 'rgb_array', or None
  render_fps: 60
  dt: 0.1              # Simulation time step (seconds)
  mode: 'single'
  num_agents: 1 

  
# Training Parameters
training:
  num_episodes: 500     # Number of training episodes
  max_steps: 1000       # Max steps per episode
  render_mode: 'human' # 'human', 'rgb_array', or None (Usually None during training)
  render_fps: 60        # Frames per second for rendering (if render_mode is 'human')
  save_frequency: 100   # Save model every N episodes
  learning_rate: 0.001 # Learning rate for the optimizer
  discount_factor: 0.99 # Discount factor for the optimizer
  rl_algo: 'reinforce'   # 'ppo', 'td3', 'sac', 'reinforce'

# Track Parameters (Example for Oval)
track:
  type: 'oval'
  length: 100.0               # Length of straight sections
  radius: 30.0                # Radius of curved sections
  width: 15.0                 # Total width of the track (2 * omega_r from image)
  start_line_x: 0.0           # X-coordinate of the start/end line center
  start_lane: 'bottom'   # 'top' or 'bottom'

# Environment Specific Configuration
environment:
  # List the observation components to include in the observation space
  # Available keys (can be expanded): 'x', 'y', 'v', 'theta', 'steer_angle', 'dist_to_centerline', ...
  observation_components: 
    - 'x'
    - 'y'
    - 'v'
    - 'theta'
    - 'steer_angle'
    - 'dist_to_centerline'

# Car Parameters
car:
  wheelbase: 2.5         # L (meters)
  mass: 1500             # Mass (kg)
  max_speed: 20.0        # m/s
  min_accel: -5.0        # m/s^2 (braking)
  max_accel: 3.0         # m/s^2
  max_steer_angle: 0.6   # radians (~34 degrees)
  width: 1.8             # For collision/visualization
  length: 4.0            # For collision/visualization
  collision_radius: 1.5  # Simplified collision check radius
  
  # --- More Realistic Physics Params --- 
  coeff_drag: 0.8         # Air resistance coefficient (Cd * A * rho / 2)
  coeff_rolling_resistance: 60.0 # Rolling resistance coefficient
  coeff_friction: 1.1      # Combined tire longitudinal friction coefficient (relative)
  coeff_cornering_stiffness: 15.0 # Tire lateral stiffness factor (simplified grip)
  max_engine_force: 4500   # Max forward force from engine (N)
  max_brake_force: 6000    # Max backward force from brakes (N)
  gravity: 9.81          # Acceleration due to gravity (m/s^2)
  # ------------------------------------ 

# Agent Configuration Details (Used in Single Agent Mode)
# The simulation script will select the config based on the chosen agent type
agent_config:
  human:
    # No specific params needed currently
    description: "Controlled by user via keyboard arrow keys."
  random:
    description: "Takes random actions within the action space."
  mpc:
    description: "Model Predictive Control agent."
    horizon: 15       # Prediction horizon (N)
    # dt will be set from simulation dt
    # Add other MPC specific parameters if needed
  rl:
    description: "Reinforcement Learning agent."
    model_path: "models/single_agent/trained_model.zip" # Path to the saved RL model
    # Add other RL specific parameters if needed (e.g., network architecture details)

# Default Agent Setup (can be used for start position, etc.)
# In single-agent mode, 'type' here is ignored, and params are taken from 'agent_config' above.
# In multi-agent mode (using config.yaml), this structure defines each agent.
agents:
  agent_0:
    # 'type' field is relevant for multi-agent config, ignored here for single-agent selection.
    start_pos_idx: 0


# RL Hyperparameters (Example - adjust based on library/algo)
rl:
  learning_rate: 0.0003
  discount_factor: 0.99
  # ... other hyperparameters